-- Check distribution of gender (includes total using ROLLUP)
SELECT 
    IFNULL(gender, 'Total') AS gender,
    COUNT(*) AS total_applications
FROM loan_applications_raw
GROUP BY gender WITH ROLLUP;

-- Purpose:
-- Examines the distribution of the gender field to detect unexpected categories or NULL values.
-- IFNULL means, if gender is NULL show 'Total', otherwise, show the actual gender value. 
-- WITH ROLLUP adds an overall total row for quick validation.

-- I used IFNULL to handle the NULL row generated by WITH ROLLUP so the grand total would display clearly as ‘Total’ instead of NULL.